[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PaCMAP"
authors = [{name = "Haiyang Huang", email = "hyhuang at cs dot duke dot edu"}]
dynamic = ["version", "description"]
